#//////////////////////////////////////////////////////////////////////////////
#   -- MAGMA (version 1.1) --
#      Univ. of Tennessee, Knoxville
#      Univ. of California, Berkeley
#      Univ. of Colorado, Denver
#      @date
#//////////////////////////////////////////////////////////////////////////////

# push previous directory
dir_stack := $(dir_stack) $(cdir)
cdir      := testing
# ----------------------------------------------------------------------


# ----------
# BLAS and auxiliary
testing_src += \
	$(cdir)/testing_zgemm.cpp	\
	$(cdir)/testing_zgemm_reduce.cpp	\
	$(cdir)/testing_zgemv.cpp	\
	$(cdir)/testing_zhemv.cpp	\
	$(cdir)/testing_zherk.cpp	\
	$(cdir)/testing_zher2k.cpp	\
	$(cdir)/testing_zsymv.cpp	\
	$(cdir)/testing_ztrmm.cpp	\
	$(cdir)/testing_ztrmv.cpp	\
	$(cdir)/testing_ztrsm.cpp	\
	$(cdir)/testing_ztrsv.cpp	\
	\
	$(cdir)/testing_blas_z.cpp	\
	$(cdir)/testing_cblas_z.cpp	\
	$(cdir)/testing_zgeadd.cpp	\
	$(cdir)/testing_zlacpy.cpp	\
	$(cdir)/testing_zlag2c.cpp	\
	$(cdir)/testing_zlange.cpp	\
	$(cdir)/testing_zlanhe.cpp	\
	$(cdir)/testing_zlarfg.cpp	\
	$(cdir)/testing_zlascl.cpp	\
	$(cdir)/testing_zlaset.cpp	\
	$(cdir)/testing_zlaset_band.cpp	\
	$(cdir)/testing_zlat2c.cpp	\
	$(cdir)/testing_znan_inf.cpp	\
	$(cdir)/testing_zprint.cpp	\
	$(cdir)/testing_zsymmetrize.cpp	\
	$(cdir)/testing_zsymmetrize_tiles.cpp	\
	$(cdir)/testing_zswap.cpp	\
	$(cdir)/testing_ztranspose.cpp	\
	\
	$(cdir)/testing_auxiliary.cpp	\
	$(cdir)/testing_constants.cpp	\
	$(cdir)/testing_operators.cpp	\
	$(cdir)/testing_parse_opts.cpp	\

# ----------
# iwocl benchmark
testing_src += \
	$(cdir)/testing_benchmark.cpp	\

# ----------
# Cholesky, GPU interface
testing_src += \
	$(cdir)/testing_zcposv_gpu.cpp	\
	\
	$(cdir)/testing_zposv_gpu.cpp	\
	$(cdir)/testing_zpotrf_gpu.cpp	\
	$(cdir)/testing_zpotrf_msub.cpp	\
	$(cdir)/testing_zpotri_gpu.cpp	\
	$(cdir)/testing_ztrtri_gpu.cpp	\
	\
	$(cdir)/testing_zpotrf_mgpu.cpp	\

# Cholesky, CPU interface
testing_src += \
	$(cdir)/testing_zposv.cpp	\
	$(cdir)/testing_zpotrf.cpp	\
	$(cdir)/testing_zpotri.cpp	\
	$(cdir)/testing_ztrtri.cpp	\

# ----------
# Symmetric indefinite, CPU interface
testing_src += \
	$(cdir)/testing_zhesv.cpp	\
	$(cdir)/testing_zhetrf.cpp	\

# ----------
# LU, GPU interface
testing_src += \
	$(cdir)/testing_zgesv_gpu.cpp	\
	$(cdir)/testing_zgetrf_gpu.cpp	\
	$(cdir)/testing_zgetrf_msub.cpp	\
	$(cdir)/testing_zgetri_gpu.cpp	\
	\
	$(cdir)/testing_zgetrf_mgpu.cpp	\

# LU, CPU interface
testing_src += \
	$(cdir)/testing_zgesv.cpp	\
	$(cdir)/testing_zgetrf.cpp	\

# ----------
# QR and least squares, GPU interface
testing_src += \
	$(cdir)/testing_zgels_gpu.cpp	\
	$(cdir)/testing_zgeqr2x_gpu.cpp	\
	$(cdir)/testing_zgeqrf_gpu.cpp	\
	$(cdir)/testing_zgeqrf_msub.cpp	\
	$(cdir)/testing_zlarfb_gpu.cpp	\
	\
	$(cdir)/testing_zgeqrf_mgpu.cpp	\

# QR, CPU interface
testing_src += \
	$(cdir)/testing_zgelqf.cpp	\
	$(cdir)/testing_zgeqlf.cpp	\
	$(cdir)/testing_zgeqrf.cpp	\
	$(cdir)/testing_zungqr.cpp	\
	$(cdir)/testing_zunmlq.cpp	\
	$(cdir)/testing_zunmql.cpp	\
	$(cdir)/testing_zunmqr.cpp	\

# ----------
# symmetric eigenvalues, CPU interface
testing_src += \
	$(cdir)/testing_zheevd.cpp	\
	$(cdir)/testing_zhetrd.cpp	\

# ----------
# non-symmetric eigenvalues
testing_src += \
	$(cdir)/testing_dgeev.cpp	\
	$(cdir)/testing_zgeev.cpp	\
	$(cdir)/testing_zgehrd.cpp	\

# ----------
# SVD
testing_src += \
	$(cdir)/testing_zgesdd.cpp	\
	$(cdir)/testing_zgesvd.cpp	\
	$(cdir)/testing_zgebrd.cpp	\
	$(cdir)/testing_zunmbr.cpp	\


# ----------------------------------------
# utilities library
libtest_src := \
	$(cdir)/magma_util.cpp		\
	$(cdir)/magma_zutil.cpp		\


# ----------------------------------------------------------------------
# pop first directory
cdir      := $(firstword $(dir_stack))
dir_stack := $(wordlist 2, $(words $(dir_stack)), $(dir_stack))
